# Generated by Django 5.2.5 on 2025-09-11 17:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='backups/')),
                ('original_file_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=500)),
                ('app_name', models.CharField(blank=True, max_length=255, null=True)),
                ('version_code', models.CharField(blank=True, max_length=50, null=True)),
                ('version_name', models.CharField(blank=True, max_length=50, null=True)),
                ('apk_file', models.BinaryField(blank=True, null=True)),
                ('apk_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('permissions', models.JSONField(blank=True, default=list, null=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='backup.backup')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='backup.backup')),
            ],
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('call_type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing'), ('missed', 'Missed')], max_length=20)),
                ('call_date', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='backup.backup')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='backup.backup')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='backup.backup')),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('minio_path', models.CharField(blank=True, max_length=500, null=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='backup.backup')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('message_type', models.CharField(blank=True, choices=[('sms', 'SMS'), ('mms', 'MMS')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='backup.backup')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='backup.backup')),
            ],
        ),
        migrations.CreateModel(
            name='RawBackupFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(max_length=500)),
                ('file_data', models.BinaryField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_files', to='backup.backup')),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_settings', to='backup.backup')),
            ],
        ),
    ]
