# Generated by Django 5.2.5 on 2025-08-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='apk_path',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='path',
        ),
        migrations.AddField(
            model_name='app',
            name='apk_file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='apk_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='backup',
            name='original_file_name',
            field=models.CharField(default='original file', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediafile',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rawbackupfile',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='original_file',
            field=models.BinaryField(),
        ),
    ]
