# Generated by Django 5.2.5 on 2025-09-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='apk_file',
        ),
        migrations.AddField(
            model_name='app',
            name='minio_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
