# Generated by Django 5.2.5 on 2025-08-13 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='permissions',
        ),
    ]
