# Generated by Django 5.2.5 on 2025-08-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_remove_app_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='permissions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
