# Generated by Django 5.2.5 on 2025-09-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_remove_app_apk_file_app_minio_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='original_file',
        ),
        migrations.AddField(
            model_name='backup',
            name='original_minio_path',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
