# Generated by Django 5.2.5 on 2025-08-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_remove_app_apk_path_remove_mediafile_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='original_file',
            field=models.FileField(upload_to='backups/'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
