# Generated by Django 5.2.5 on 2025-08-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_app_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='media_type',
            field=models.CharField(blank=True, choices=[('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
