# Generated by Django 5.2.5 on 2025-08-15 03:23

import backup.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0004_alter_mediafile_media_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='file_data',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=backup.models.media_file_path),
        ),
    ]
