# Generated by Django 5.2.5 on 2025-09-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0005_remove_mediafile_file_data_mediafile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
